# Generated by Django 3.1.1 on 2020-12-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='case',
            fields=[
                ('report_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('nat_id', models.CharField(blank=True, max_length=14, null=True)),
                ('goods', models.CharField(max_length=40)),
                ('price', models.FloatField(max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=40, null=True)),
                ('bank_num', models.CharField(blank=True, max_length=20, null=True)),
                ('province', models.CharField(blank=True, max_length=40, null=True)),
                ('trans_date', models.DateTimeField(blank=True, null=True, verbose_name='Transaction date')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('website', models.URLField(blank=True, null=True, verbose_name='Merchant Website')),
                ('details', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
